### ISSUE TITLE
FYI: Hero Login Links don't display until a service page is published (i.e., they don't display when first added in draft view)

### ISSUE THREAD

**Issue by jssharma** [Stony-Brook-University/doitsbu#32]
site: https://it.stonybrook.edu/services/degree-works (I've already published the page with the login link, so the issue won't appear on this page anymore)

**Draft View:**
![image](https://cloud.githubusercontent.com/assets/22774610/19321250/414d7e20-9082-11e6-8724-1abcf878f3b0.png)

Published View:
![image](https://cloud.githubusercontent.com/assets/22774610/19321284/6c6f42a0-9082-11e6-8e3a-7a5343a0feb5.png)

**Comment by SBUDoIT** [comment]
Issue related to the fact that in preprocess_page, the published version of node is supplied rather than the draft, even when viewing the draft page. 

This seems to be  a workbench moderation issue: https://www.drupal.org/node/2536386#comment-11723127 -- however when I applied the patch, $vars['node'] was instead empty instead of having the draft value. I opted to instead use an if statement to load the draft version in the preprocess hook.
